### PR TITLE
Add support for Real-CUGAN

### PR DESCRIPTION
**Pull request by RunDevelopment**
https://github.com/bilibili/ailab/tree/main/Real-CUGAN

This architecture comes with an interesting detail: pro mode. In pro mode, the input range of mapped to [0.15, 0.85]. This apparently [reduces haloing](https://github.com/bilibili/ailab/blob/main/Real-CUGAN/Changelog_CN.md). The interesting bit here is that Real-CUGAN detects pro models using [a `pro` key in the state dict](https://github.com/bilibili/ailab/blob/2799af78ef105b414cc4b796c67c8511acdcdf6f/Real-CUGAN/upcunet_v3.py#L1263). This `pro` key is mapped to the integer 1 (not a tensor, just the int 1).

I'm bringing this up, because it means that saving a loaded pro model will **lose the `pro` key**. Since it's not a tensor, it will not be saved in the `.pth`. 

I think it would probably be okay to just accept this as a bug for now, but it's something we should fix eventually.

### CODE REVIEW

**Comment by joeyballentine** [comment]
The goal of spandrel is to be able to load models and use them properly. Any changes we have to make to a state dict to get that to happen are fine IMO even if that means it doesn't re-save properly. IMO, that's not our problem. We already technically "break" esrgan models by modifying their keynames, and we "break" any model that's saved with a load-key (params_ema for example).

**Comment by RunDevelopment** [comment]
> We already technically "break" esrgan models by modifying their keynames, and we "break" any model that's saved with a load-key (params_ema for example).

That's fine IMO, because spandrel can still correctly read the models we save ourselves. But that's not the case for Real-CUGAN pro models. If you use spandrel to load a pro model, save it, and the load the saved model, it will not be correctly loaded anymore.

**Comment by joeyballentine** [comment]
Hmmm... Yeah I guess that's different then. In that case, yeah that's probably something we should try to solve.

Maybe we could have something like the call API where we have descriptor methods for saving that are model specific?

**Comment by RunDevelopment** [comment]
> Maybe we could have something like the call API where we have descriptor methods for saving that are model specific?

I guess. But the issue with that is that we would have 2 (potentially) different state dicts per model. One state dict of the model itself (`model_desc.model.state_dict()`) and the modified state dict of the new API. 

Well, since this isn't a huge problem for now, let's just make an issue for this after merging Real-CUGAN and talk about a general solution there.

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
