### PR TITLE
Add support for SGNet

### PR DESCRIPTION
**Pull request by RunDevelopment**
Blocked by https://github.com/yanzq95/SGNet/issues/6

This adds support for [SGNet](https://github.com/yanzq95/SGNet). The implementation is currently incomplete because the pretrained models aren't working.

### CODE REVIEW

**Comment by joeyballentine** [comment]
@RunDevelopment is this good to go now that the blocker is resolved?

**Comment by RunDevelopment** [comment]
Sorry, I forgot to answer.

The blocker is resolved, but I'm not sure whether it even makes sense to add it. My intention was to use this for things other than depth map upscaling. Theoretically, a model that works for depth maps should also work for other piece-wise smooth textures. This didn't work at all, so I don't know what we would even use this for.

**Comment by joeyballentine** [comment]
Ok then let's just scrap it for now

**Comment by RunDevelopment** [comment]
Honestly, yeah. If we ever want to add support for this or similar models again, we can just revive this PR.

**Pull request closed without merging**
