### PR TITLE
Add support for ATD

### PR DESCRIPTION
**Pull request by RunDevelopment**
This adds support for [ATD](https://github.com/LabShuHangGU/Adaptive-Token-Dictionary).

### CODE REVIEW

**Comment by RunDevelopment** [comment]
This is so weird. Why do I get vastly different outputs in CI?

**Comment by joeyballentine** [comment]
CPU vs GPU?

**Comment by RunDevelopment** [comment]
I use CPU for tests locally as well.

**Comment by joeyballentine** [comment]
maybe its linux thats the problem? i have no idea what else it could be

**Comment by RunDevelopment** [comment]
Okay, so I just did test runs on CPU vs GPU. It seems like ATD is *highly sensitive* to floating point impression. When I compare the output of my CPU vs GPU, I get the same type of large error as we see with CI. Despite the large error, the two outputs are visually the same, so I think I'm going to add another error metric to account for this.

**Comment by RunDevelopment** [comment]
Finally.

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
